### ISSUE TITLE
message generation dependencies

### ISSUE THREAD

**Issue by pallegro** [ros-planning/shape_tools#3]
catkin_make attempts to build shape_tools before generating headers for shape_msgs.  I'd make a pull request but I'm not confident my solution is the standard way to prevent this.  But according to http://wiki.ros.org/catkin/conceptual_overview I added

add_dependencies(${PROJECT_NAME} shape_msgs_gencpp)
add_dependencies(${PROJECT_NAME} visualization_msgs_gencpp)

to  CMakeLists.txt.

**Comment by acornacorn** [comment]
That looks right.  Go ahead and do the pull request and I'll merge it assuming it looks good.
Thanks!
Acorn

**Comment by isucan** [comment]
The method you mention would work, but it is deprecated. I think the catkin way of doing this is adding this line:

```
add_dependencies(${PROJECT_NAME} ${catkin_EXPORTED_TARGETS})
```

**Comment by davetcoleman** [comment]
This repo/package has been merged with geometric_shapes, if this issue persists please re-open at https://github.com/ros-planning/geometric_shapes
