### ISSUE TITLE
Merge with geometric_shapes

### ISSUE THREAD

**Issue by davetcoleman** [ros-planning/shape_tools#4]
Why does this package exist along with https://github.com/ros-planning/geometric_shapes ? Seems like they should be one.

**Comment by mikeferguson** [comment]
@davetcoleman just noticed this comment -- I concur that they should merged at some point, not sure the scope of changes to downstream projects though.

**Comment by davetcoleman** [comment]
@isucan would have the best advice. I'm willing to make the PR though

**Comment by isucan** [comment]
This was a dependency issue. I think I wanted to avoid depending on the (relatively heavy) geometric_shapes from rviz. shape_tools is relatively simple. I am fine with merging them as well -- it bugged me too.

**Comment by davetcoleman** [comment]
I will move forward with creating a jade-devel branch for `shape_tools` that will be empty with a note saying it has been moved to the other package. I'll duplicate the functionality in the indigo-devel branch of `geometric_shapes` and go ahead and switch moveit to the new location now, once the changes to `geometric_shapes` are released. Sound like a good plan?

**Comment by davetcoleman** [comment]
I believe the migration is complete - all necessary PRs have been merged. 

For ROS Jade I think we should merge https://github.com/ros-planning/shape_tools/pull/5 which effectively kills shape_tools
